# Generated by Django 5.2.12 on 2026-03-17 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='ERP_ServicesBI.fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
