# Generated by Django 5.2.12 on 2026-04-07 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='ERP_ServicesBI.deposito', verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
