# Generated by Django 5.2.12 on 2026-04-07 16:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0002_inventario_deposito_alter_inventario_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnotafiscalentrada',
            options={'verbose_name': 'Item NF Entrada', 'verbose_name_plural': 'Itens NF Entrada'},
        ),
        migrations.AlterModelOptions(
            name='itemnotafiscalsaida',
            options={'verbose_name': 'Item NF Saída', 'verbose_name_plural': 'Itens NF Saída'},
        ),
        migrations.AlterModelOptions(
            name='notafiscalentrada',
            options={'ordering': ['-data_emissao', '-id'], 'verbose_name': 'Nota Fiscal de Entrada', 'verbose_name_plural': 'Notas Fiscais de Entrada'},
        ),
        migrations.AlterModelOptions(
            name='notafiscalsaida',
            options={'ordering': ['-data_emissao', '-id'], 'verbose_name': 'Nota Fiscal de Saída', 'verbose_name_plural': 'Notas Fiscais de Saída'},
        ),
        migrations.RenameField(
            model_name='notafiscalentrada',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='notafiscalsaida',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.AlterUniqueTogether(
            name='notafiscalentrada',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemnotafiscalentrada',
            name='preco_total',
        ),
        migrations.RemoveField(
            model_name='itemnotafiscalentrada',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='itemnotafiscalsaida',
            name='preco_total',
        ),
        migrations.RemoveField(
            model_name='itemnotafiscalsaida',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='notafiscalsaida',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='notafiscalsaida',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='notafiscalsaida',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='notafiscalsaida',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='notafiscalsaida',
            name='pedido_origem',
        ),
        migrations.AddField(
            model_name='itemnotafiscalentrada',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='itemnotafiscalsaida',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=44, verbose_name='Chave de Acesso'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Recebimento'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_nf', to='ERP_ServicesBI.deposito', verbose_name='Depósito Destino'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='serie',
            field=models.CharField(default='1', max_length=10, verbose_name='Série'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Frete'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='valor_impostos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Impostos'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='valor_produtos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Produtos'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='deposito_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_nf', to='ERP_ServicesBI.deposito', verbose_name='Depósito Origem'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='serie',
            field=models.CharField(default='1', max_length=10, verbose_name='Série'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Frete'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='valor_impostos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Impostos'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='valor_produtos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Produtos'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='ERP_ServicesBI.produto'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='quantidade_contada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd. Contada'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='quantidade_fisica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd. Física'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='quantidade_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd. Sistema'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalentrada',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=15, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalentrada',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_nf', to='ERP_ServicesBI.produto'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalentrada',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalsaida',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalsaida',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas_nf', to='ERP_ServicesBI.produto'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalsaida',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='data_emissao',
            field=models.DateField(verbose_name='Data Emissão'),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_entrada', to='ERP_ServicesBI.fornecedor'),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='numero_nf',
            field=models.CharField(max_length=20, verbose_name='Número NF'),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='notafiscalsaida',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_saida', to='ERP_ServicesBI.cliente'),
        ),
        migrations.AlterField(
            model_name='notafiscalsaida',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Emissão'),
        ),
        migrations.AlterField(
            model_name='notafiscalsaida',
            name='numero_nf',
            field=models.CharField(max_length=20, verbose_name='Número NF'),
        ),
        migrations.AlterField(
            model_name='notafiscalsaida',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notafiscalsaida',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total'),
        ),
        migrations.AlterUniqueTogether(
            name='iteminventario',
            unique_together={('inventario', 'produto')},
        ),
        migrations.RemoveField(
            model_name='notafiscalentrada',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='notafiscalentrada',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='notafiscalentrada',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='notafiscalentrada',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='notafiscalentrada',
            name='pedido_origem',
        ),
    ]
