# Generated by Django 5.2.12 on 2026-04-07 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0003_alter_itemnotafiscalentrada_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciaestoque',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='transferenciaestoque',
            name='origem',
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='data_transferencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='itemtransferencia',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itemtransferencia',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='data_efetivacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='deposito_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='ERP_ServicesBI.deposito', verbose_name='Depósito de Destino'),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='deposito_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origem', to='ERP_ServicesBI.deposito', verbose_name='Depósito de Origem'),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('concluida', 'Concluída'), ('efetivada', 'Efetivada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='itemtransferencia',
            unique_together={('transferencia', 'produto')},
        ),
    ]
