# Generated by Django 5.2.12 on 2026-03-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0003_alter_empresa_options_fornecedor_nome_razao_social_and_more'),
    ]

    operations = [
    ]
