# Generated by Django 5.2.12 on 2026-04-08 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0004_remove_transferenciaestoque_destino_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemtransferencia',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transferenciaestoque',
            name='data_transferencia',
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='data_saida',
            field=models.DateField(blank=True, help_text='Data em que a mercadoria foi entregue', null=True, verbose_name='Data Saída'),
        ),
        migrations.AddField(
            model_name='notafiscalsaida',
            name='pedido_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_saida', to='ERP_ServicesBI.pedidovenda', verbose_name='Pedido de Venda'),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='destino',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='origem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemtransferencia',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.produto'),
        ),
        migrations.AlterField(
            model_name='itemtransferencia',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='data_efetivacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='deposito_destino',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='deposito_origem',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('efetivada', 'Efetivada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
