# Generated by Django 5.2.12 on 2026-04-11 20:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0005_alter_itemtransferencia_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemMovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia', 'Transferência'), ('ajuste', 'Ajuste')], default='entrada', max_length=20, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=15, null=True, verbose_name='Preço Unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deposito_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_entrada', to='ERP_ServicesBI.deposito', verbose_name='Depósito Destino')),
                ('deposito_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_saida', to='ERP_ServicesBI.deposito', verbose_name='Depósito Origem')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_movimentacao', to='ERP_ServicesBI.movimentacaoestoque', verbose_name='Movimentação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP_ServicesBI.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Movimentação',
                'verbose_name_plural': 'Itens de Movimentação',
                'ordering': ['movimentacao', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='ItemCondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(default=1, verbose_name='Nº Parcela')),
                ('dias', models.PositiveIntegerField(default=30, verbose_name='Dias')),
                ('percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Percentual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condicao_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ERP_ServicesBI.condicaopagamento', verbose_name='Condição de Pagamento')),
            ],
            options={
                'verbose_name': 'Item de Condição de Pagamento',
                'verbose_name_plural': 'Itens de Condição de Pagamento',
                'ordering': ['condicao_pagamento', 'numero_parcela'],
                'unique_together': {('condicao_pagamento', 'numero_parcela')},
            },
        ),
        migrations.CreateModel(
            name='PosicaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_inicial', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Quantidade Inicial')),
                ('quantidade_entradas', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Entradas')),
                ('quantidade_saidas', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Saídas')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, verbose_name='Quantidade Atual')),
                ('valor_unitario_medio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Custo Médio')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total')),
                ('data_referencia', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Referência')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posicoes_estoque', to='ERP_ServicesBI.deposito', verbose_name='Depósito')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posicoes_estoque', to='ERP_ServicesBI.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Posição de Estoque',
                'verbose_name_plural': 'Posições de Estoque',
                'db_table': 'estoque_posicao',
                'ordering': ['-data_referencia', 'produto__descricao'],
                'unique_together': {('produto', 'deposito', 'data_referencia')},
            },
        ),
    ]
