# Generated by Django 5.2.12 on 2026-04-11 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0006_marca_itemmovimentacaoestoque_itemcondicaopagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#007bff', help_text='Código HEX para identificação', max_length=7, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('tipo', models.CharField(choices=[('rodoviario', 'Rodoviário'), ('aereo', 'Aéreo'), ('maritimo', 'Marítimo'), ('ferroviario', 'Ferroviário'), ('outro', 'Outro')], default='rodoviario', max_length=20, verbose_name='Tipo')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('saldo_inicial_extrato', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial Extrato')),
                ('saldo_final_extrato', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Final Extrato')),
                ('saldo_inicial_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial Sistema')),
                ('saldo_final_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Final Sistema')),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Diferença')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('conciliado', 'Conciliado'), ('divergente', 'Divergente')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='ERP_ServicesBI.contabancaria', verbose_name='Conta Bancária')),
                ('extrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacao', to='ERP_ServicesBI.extratobancario', verbose_name='Extrato Importado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conciliação Bancária',
                'verbose_name_plural': 'Conciliações Bancárias',
                'ordering': ['-data_fim'],
            },
        ),
        migrations.CreateModel(
            name='FluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor')),
                ('periodo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Período')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('realizado', models.BooleanField(default=False, help_text='Se já foi executado/realizado', verbose_name='Realizado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxos_caixa', to='ERP_ServicesBI.categoriafinanceira')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxos_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fluxo de Caixa',
                'verbose_name_plural': 'Fluxos de Caixa',
                'ordering': ['-data', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='PlanejadoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('projeto', 'Por Projeto'), ('categoria', 'Por Categoria'), ('centro_custo', 'Por Centro de Custo'), ('geral', 'Geral')], default='geral', max_length=20, verbose_name='Tipo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(blank=True, null=True, verbose_name='Mês')),
                ('trimestre', models.IntegerField(blank=True, null=True, verbose_name='Trimestre')),
                ('periodo', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Período')),
                ('receitas_planejadas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Receitas Planejadas')),
                ('despesas_planejadas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Despesas Planejadas')),
                ('saldo_planejado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Planejado')),
                ('receitas_realizadas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Receitas Realizadas')),
                ('despesas_realizadas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Despesas Realizadas')),
                ('saldo_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Realizado')),
                ('variacao_receitas', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Variação Receitas (%)')),
                ('variacao_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Variação Despesas (%)')),
                ('variacao_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Variação Saldo (%)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planejado_realizado', to='ERP_ServicesBI.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planejado_realizado', to='ERP_ServicesBI.centrocusto')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planejado_realizado', to='ERP_ServicesBI.projeto')),
            ],
            options={
                'verbose_name': 'Planejado x Realizado',
                'verbose_name_plural': 'Planejados x Realizados',
                'ordering': ['-ano', '-mes', 'tipo'],
            },
        ),
    ]
