# Generated by Django 5.2.12 on 2026-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0006_alter_cliente_bairro_alter_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='solicitante',
            field=models.CharField(max_length=100, verbose_name='Solicitante'),
        ),
    ]
