# Generated by Django 5.2.12 on 2026-03-23 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0007_alter_cotacao_solicitante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoMae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título/Descrição')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('data_solicitacao', models.DateField(auto_now_add=True, verbose_name='Data Solicitação')),
                ('data_limite_resposta', models.DateField(blank=True, null=True, verbose_name='Data Limite Resposta')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada aos Fornecedores'), ('respondida', 'Cotações Recebidas'), ('em_analise', 'Em Análise'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_mae_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Cotação Mãe',
                'verbose_name_plural': 'Cotações Mãe',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Contato')),
                ('contato_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do Contato')),
                ('contato_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('valor_total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total Bruto')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Frete')),
                ('valor_total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total Líquido')),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100, verbose_name='Condição de Pagamento')),
                ('prazo_entrega_dias', models.IntegerField(default=0, verbose_name='Prazo Entrega (dias)')),
                ('disponibilidade_produtos', models.CharField(default='100%', max_length=50, verbose_name='% Disponibilidade Produtos')),
                ('arquivo_origem', models.FileField(blank=True, null=True, upload_to='cotacoes_fornecedor/%Y/%m/', verbose_name='Arquivo Original')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('importada', 'Importada'), ('processada', 'Processada'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data Envio')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data Recebimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.fornecedor', verbose_name='Fornecedor')),
                ('cotacao_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_fornecedor', to='ERP_ServicesBI.cotacaomae', verbose_name='Cotação Mãe')),
            ],
            options={
                'verbose_name': 'Cotação do Fornecedor',
                'verbose_name_plural': 'Cotações dos Fornecedores',
                'ordering': ['-created_at'],
                'unique_together': {('cotacao_mae', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_manual', models.CharField(blank=True, max_length=255, verbose_name='Descrição (se não cadastrado)')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade')),
                ('unidade_medida', models.CharField(default='UN', max_length=20, verbose_name='Unidade de Medida')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('cotacao_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitados', to='ERP_ServicesBI.cotacaomae', verbose_name='Cotação Mãe')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.produto', verbose_name='Produto (se cadastrado)')),
            ],
            options={
                'verbose_name': 'Item Solicitado',
                'verbose_name_plural': 'Itens Solicitados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_fornecedor', models.CharField(max_length=255, verbose_name='Descrição no Arquivo')),
                ('codigo_fornecedor', models.CharField(blank=True, max_length=50, verbose_name='Código do Fornecedor')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade')),
                ('unidade_medida', models.CharField(blank=True, max_length=20, verbose_name='Unidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Unitário')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Total')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('prazo_entrega_item', models.IntegerField(blank=True, null=True, verbose_name='Prazo Específico (dias)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('match_automatico', models.BooleanField(default=False, verbose_name='Match Automático')),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score de Match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cotacao_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ERP_ServicesBI.cotacaofornecedor', verbose_name='Cotação do Fornecedor')),
                ('item_solicitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_recebidas', to='ERP_ServicesBI.itemsolicitado', verbose_name='Item Solicitado (vinculado)')),
            ],
            options={
                'verbose_name': 'Item da Cotação do Fornecedor',
                'verbose_name_plural': 'Itens das Cotações dos Fornecedores',
                'ordering': ['id'],
            },
        ),
    ]
