# Generated by Django 5.2.12 on 2026-03-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0008_cotacaomae_cotacaofornecedor_itemsolicitado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocompra',
            name='cotacao_origem',
        ),
        migrations.RemoveField(
            model_name='itemcotacao',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='itemcotacao',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='notafiscalentrada',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='notafiscalsaida',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='Cotacao',
        ),
        migrations.DeleteModel(
            name='ItemCotacao',
        ),
    ]
