# Generated by Django 5.2.12 on 2026-03-25 22:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0009_remove_pedidocompra_cotacao_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaofornecedor',
            name='nota_confiabilidade',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nota de Confiabilidade (1-10)'),
        ),
        migrations.AddField(
            model_name='itemcotacaofornecedor',
            name='melhor_prazo',
            field=models.BooleanField(default=False, verbose_name='Melhor Prazo'),
        ),
        migrations.AddField(
            model_name='itemcotacaofornecedor',
            name='melhor_preco',
            field=models.BooleanField(default=False, verbose_name='Melhor Preço'),
        ),
        migrations.AddField(
            model_name='itemcotacaofornecedor',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cotacao_origem', to='ERP_ServicesBI.pedidocompra', verbose_name='Pedido de Compra Gerado'),
        ),
        migrations.AddField(
            model_name='itemcotacaofornecedor',
            name='selecionado',
            field=models.BooleanField(default=False, verbose_name='Selecionado para Compra'),
        ),
        migrations.AddField(
            model_name='itemcotacaofornecedor',
            name='sugerido',
            field=models.BooleanField(default=False, verbose_name='Sugerido pelo Sistema'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='item_cotacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido_gerados', to='ERP_ServicesBI.itemcotacaofornecedor', verbose_name='Item da Cotação Origem'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Condição de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='cotacao_fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerados', to='ERP_ServicesBI.cotacaofornecedor', verbose_name='Cotação do Fornecedor'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='cotacao_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerados', to='ERP_ServicesBI.cotacaomae', verbose_name='Cotação de Origem'),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalentrada',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalentrada',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='quantidade_recebida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
