# Generated by Django 5.2.12 on 2026-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0011_vendedor_alter_orcamento_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('dias', models.IntegerField(default=0, verbose_name='Dias')),
                ('parcelas', models.IntegerField(default=1, verbose_name='Parcelas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Condição de Pagamento',
                'verbose_name_plural': 'Condições de Pagamento',
                'ordering': ['descricao'],
            },
        ),
    ]
