# Generated by Django 5.2.12 on 2026-03-26 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0013_formapagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaDRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 1.0, 1.1, 2.0, 3.0', max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(help_text='Nome da linha na DRE', max_length=100, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('grupo', 'Grupo/Título'), ('soma_categoria', 'Soma de Categorias'), ('calculo', 'Cálculo/Subtotal'), ('imposto', 'Cálculo de Imposto')], default='soma_categoria', max_length=20, verbose_name='Tipo')),
                ('natureza', models.CharField(choices=[('receita', 'Receita (+)'), ('despesa', 'Despesa (-)'), ('resultado', 'Resultado (=)')], default='despesa', max_length=10, verbose_name='Natureza')),
                ('grupos_dre', models.CharField(blank=True, help_text='Lista separada por vírgula dos grupo_dre a somar. Ex: receita_bruta,outras_receitas', max_length=255, verbose_name='Grupos DRE')),
                ('formula', models.CharField(blank=True, help_text='Códigos das linhas para cálculo. Ex: 1.0-2.0 ou 3.0+4.0-5.0', max_length=255, verbose_name='Fórmula')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('nivel', models.IntegerField(default=0, help_text='0=Principal, 1=Subitem, 2=Detalhe', verbose_name='Nível de Indentação')),
                ('negrito', models.BooleanField(default=False, help_text='Destacar linha em negrito', verbose_name='Negrito')),
                ('visivel', models.BooleanField(default=True, help_text='Exibir no relatório', verbose_name='Visível')),
                ('regime_especifico', models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], help_text='Deixe vazio para exibir em todos os regimes', max_length=15, null=True, verbose_name='Regime Específico')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Linha DRE',
                'verbose_name_plural': 'Linhas DRE',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='grupo_dre',
            field=models.CharField(choices=[('receita_bruta', 'Receita Operacional Bruta'), ('deducoes', 'Deduções da Receita'), ('outras_receitas', 'Outras Receitas Operacionais'), ('cmv', 'CMV - Custo das Mercadorias Vendidas'), ('cpv', 'CPV - Custo dos Produtos Vendidos'), ('csv', 'CSV - Custo dos Serviços Prestados'), ('despesa_vendas', 'Despesas com Vendas'), ('despesa_admin', 'Despesas Administrativas'), ('despesa_pessoal', 'Despesas com Pessoal'), ('depreciacao', 'Depreciação e Amortização'), ('outras_despesas', 'Outras Despesas Operacionais'), ('receita_financeira', 'Receitas Financeiras'), ('despesa_financeira', 'Despesas Financeiras'), ('impostos_lucro', 'Impostos sobre o Lucro (IR/CSLL)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoDRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_tributario', models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], default='simples', max_length=15, verbose_name='Regime Tributário')),
                ('atividade_principal', models.CharField(choices=[('comercio', 'Comércio'), ('servico', 'Serviços'), ('industria', 'Indústria'), ('misto', 'Misto')], default='comercio', max_length=15, verbose_name='Atividade Principal')),
                ('aliquota_simples', models.DecimalField(decimal_places=2, default=6.0, help_text='Alíquota efetiva do Simples Nacional', max_digits=5, verbose_name='Alíquota Simples (%)')),
                ('percentual_presuncao_comercio', models.DecimalField(decimal_places=2, default=8.0, help_text='Percentual de presunção para comércio (8%)', max_digits=5, verbose_name='% Presunção Comércio')),
                ('percentual_presuncao_servico', models.DecimalField(decimal_places=2, default=32.0, help_text='Percentual de presunção para serviços (32%)', max_digits=5, verbose_name='% Presunção Serviços')),
                ('aliquota_irpj', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Alíquota IRPJ (%)')),
                ('aliquota_irpj_adicional', models.DecimalField(decimal_places=2, default=10.0, help_text='Adicional sobre lucro excedente a R$ 20.000/mês', max_digits=5, verbose_name='Alíquota IRPJ Adicional (%)')),
                ('aliquota_csll', models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name='Alíquota CSLL (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_dre', to='ERP_ServicesBI.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração DRE',
                'verbose_name_plural': 'Configurações DRE',
            },
        ),
        migrations.CreateModel(
            name='RelatorioDRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('regime_tributario', models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=15, verbose_name='Regime Tributário')),
                ('receita_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deducoes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('receita_liquida', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lucro_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('despesas_operacionais', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('resultado_operacional', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('resultado_financeiro', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('resultado_antes_ir', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impostos_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lucro_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dados_json', models.JSONField(blank=True, default=dict, verbose_name='Dados Completos (JSON)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('aprovado', 'Aprovado')], default='rascunho', max_length=15, verbose_name='Status')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_dre', to='ERP_ServicesBI.empresa', verbose_name='Empresa')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_dre_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Relatório DRE',
                'verbose_name_plural': 'Relatórios DRE',
                'ordering': ['-data_fim', '-gerado_em'],
                'unique_together': {('empresa', 'data_inicio', 'data_fim')},
            },
        ),
        migrations.CreateModel(
            name='ItemRelatorioDRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor')),
                ('valor_anterior', models.DecimalField(decimal_places=2, default=0, help_text='Para análise comparativa', max_digits=15, verbose_name='Valor Período Anterior')),
                ('percentual_vertical', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='% Vertical')),
                ('percentual_horizontal', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='% Horizontal')),
                ('linha_dre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_relatorio', to='ERP_ServicesBI.linhadre', verbose_name='Linha DRE')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ERP_ServicesBI.relatoriodre', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Item do Relatório DRE',
                'verbose_name_plural': 'Itens do Relatório DRE',
                'ordering': ['linha_dre__ordem'],
                'unique_together': {('relatorio', 'linha_dre')},
            },
        ),
    ]
