# Generated by Django 5.2.12 on 2026-03-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0014_linhadre_alter_categoriafinanceira_grupo_dre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='tipo',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('vendas', 'Vendas'), ('producao', 'Produção'), ('financeiro', 'Financeiro'), ('rh', 'Recursos Humanos'), ('ti', 'Tecnologia'), ('servicos', 'Serviços'), ('outros', 'Outros')], max_length=20),
        ),
    ]
