# Generated by Django 5.2.12 on 2026-03-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0015_alter_centrocusto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='percentual_comissao',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='apelido',
            field=models.CharField(blank=True, help_text='Como prefere ser chamado', max_length=50, null=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='comissao_padrao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual padrão sobre vendas', max_digits=5, verbose_name='Comissão Padrão (%)'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(blank=True, help_text='Formatos: JPG, PNG. Máx: 2MB', null=True, upload_to='vendedores/fotos/%Y/%m/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(default='sem-email@empresa.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='meta_vendas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Meta em reais (opcional)', max_digits=12, null=True, verbose_name='Meta de Vendas Mensal'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterModelTable(
            name='vendedor',
            table='cadastro_vendedor',
        ),
    ]
