# Generated by Django 5.2.12 on 2026-03-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0016_remove_vendedor_percentual_comissao_vendedor_apelido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
