# Generated by Django 5.2.12 on 2026-03-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0017_fornecedor_limite_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condicao_pagamento_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_condicao', to='ERP_ServicesBI.condicaopagamento', verbose_name='Condição de Pagamento Padrão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pagamento_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_forma', to='ERP_ServicesBI.formapagamento', verbose_name='Forma de Pagamento Padrão'),
        ),
    ]
