# Generated by Django 5.2.12 on 2026-03-28 14:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0018_cliente_condicao_pagamento_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicaopagamento',
            name='dias',
        ),
        migrations.AddField(
            model_name='condicaopagamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condicaopagamento',
            name='dias_primeira_parcela',
            field=models.IntegerField(default=0, help_text='Dias para a primeira parcela (0 = à vista)', verbose_name='Dias 1ª Parcela'),
        ),
        migrations.AddField(
            model_name='condicaopagamento',
            name='periodicidade',
            field=models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Periodicidade'),
        ),
        migrations.AlterField(
            model_name='condicaopagamento',
            name='parcelas',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Parcelas'),
        ),
    ]
