# Generated by Django 5.2.12 on 2026-03-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0019_remove_condicaopagamento_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='condicao_pagamento_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_condicao', to='ERP_ServicesBI.condicaopagamento', verbose_name='Condição de Pagamento Padrão'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='forma_pagamento_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_forma', to='ERP_ServicesBI.formapagamento', verbose_name='Forma de Pagamento Padrão'),
        ),
    ]
