# Generated by Django 5.2.12 on 2026-03-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0020_fornecedor_condicao_pagamento_padrao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaProduto',
        ),
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria de Produto', 'verbose_name_plural': 'Categorias de Produtos'},
        ),
        migrations.AlterModelTable(
            name='categoriaproduto',
            table='cadastro_categoriaproduto',
        ),
    ]
