# Generated by Django 5.2.12 on 2026-03-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0021_rename_categoria_categoriaproduto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaofornecedor',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de Pagamento'),
        ),
    ]
