# Generated by Django 5.2.12 on 2026-03-31 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0022_cotacaofornecedor_forma_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
