# Generated by Django 5.2.12 on 2026-04-01 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0023_pedidocompra_forma_pagamento_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedidocompra',
            options={'ordering': ['id'], 'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedidocompra',
            options={'ordering': ['-data_pedido'], 'permissions': [('pode_aprovar_pedido_nivel_1', 'Pode aprovar pedidos nível 1'), ('pode_aprovar_pedido_nivel_2', 'Pode aprovar pedidos nível 2'), ('pode_aprovar_pedido_nivel_3', 'Pode aprovar pedidos nível 3'), ('pode_receber_pedido', 'Pode receber pedidos'), ('pode_cancelar_pedido', 'Pode cancelar pedidos')], 'verbose_name': 'Pedido de Compra', 'verbose_name_plural': 'Pedidos de Compra'},
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='data_ultimo_recebimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Último Recebimento'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='divergencia_encontrada',
            field=models.BooleanField(default=False, verbose_name='Divergência Encontrada?'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='observacao_divergencia',
            field=models.TextField(blank=True, verbose_name='Observação da Divergência'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='preco_unitario_recebido',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Preço Unitário Recebido'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='quantidade_conferida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Conferida (Física)'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='recebido_completo',
            field=models.BooleanField(default=False, verbose_name='Recebido Completo?'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='tipo_divergencia',
            field=models.CharField(blank=True, choices=[('quantidade_maior', 'Quantidade Maior que o Pedido'), ('quantidade_menor', 'Quantidade Menor que o Pedido'), ('preco_diferente', 'Preço Diferente do Pedido'), ('qualidade', 'Problema de Qualidade'), ('atraso', 'Atraso na Entrega'), ('produto_errado', 'Produto Errado'), ('avaria', 'Avaria no Transporte')], max_length=50, verbose_name='Tipo de Divergência'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='aprovador_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_para_aprovar', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador Atual'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='conta_pagar_gerada',
            field=models.BooleanField(default=False, verbose_name='Conta a Pagar Gerada?'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='data_recebimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='movimento_estoque_gerado',
            field=models.BooleanField(default=False, verbose_name='Movimento de Estoque Gerado?'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='nivel_aprovacao_atual',
            field=models.IntegerField(default=0, verbose_name='Nível de Aprovação Atual'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='nivel_aprovacao_necessario',
            field=models.IntegerField(default=0, help_text='0 = Não precisa de aprovação', verbose_name='Nível de Aprovação Necessário'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='nota_fiscal_vinculada',
            field=models.BooleanField(default=False, verbose_name='Nota Fiscal Vinculada?'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='observacao_recebimento',
            field=models.TextField(blank=True, verbose_name='Observações do Recebimento'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='prazo_entrega_dias',
            field=models.IntegerField(default=0, verbose_name='Prazo de Entrega (dias)'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='usuario_aprovacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Aprovou'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='usuario_cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Cancelou'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='usuario_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Recebeu'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ERP_ServicesBI.pedidocompra', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='ERP_ServicesBI.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='quantidade_recebida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Recebida'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='data_prevista_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_aprovacao', 'Em Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('pendente_entrega', 'Pendente de Entrega'), ('parcial', 'Entrega Parcial'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='PedidoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('aprovou', 'Aprovou'), ('rejeitou', 'Rejeitou'), ('encaminhou', 'Encaminhou')], max_length=20, verbose_name='Ação')),
                ('nivel', models.IntegerField(help_text='Nível de aprovação em que a ação foi tomada', verbose_name='Nível da Ação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_aprovacoes', to='ERP_ServicesBI.pedidocompra', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Aprovação',
                'verbose_name_plural': 'Históricos de Aprovação',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegraAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Regra')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Mínimo (R$)')),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Máximo (R$)')),
                ('nivel', models.IntegerField(help_text='1=Primeiro nível, 2=Segundo, etc.', verbose_name='Nível de Aprovação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo_aprovador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_aprovacao', to='auth.group', verbose_name='Grupo Aprovador')),
            ],
            options={
                'verbose_name': 'Regra de Aprovação',
                'verbose_name_plural': 'Regras de Aprovação',
                'ordering': ['nivel', 'valor_maximo'],
                'unique_together': {('nivel', 'grupo_aprovador')},
            },
        ),
    ]
