# Generated by Django 5.2.12 on 2026-04-01 16:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_ServicesBI', '0024_alter_itempedidocompra_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'db_table': 'estoque_deposito',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidade_medida',
            },
        ),
        migrations.AlterUniqueTogether(
            name='notafiscalentrada',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='regraaprovacao',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='relatoriodre',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventario',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01', verbose_name='Data Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='itemnotafiscalentrada',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='itemnotafiscalentrada',
            name='unidade_medida',
            field=models.CharField(default='UN', max_length=10, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='itemnotafiscalentrada',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itemnotafiscalentrada',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='documento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Documento Referência'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='ERP_ServicesBI.pedidocompra'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='condicao_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_entrada', to='ERP_ServicesBI.condicaopagamento'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_entrada', to='ERP_ServicesBI.formapagamento'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='modelo',
            field=models.CharField(default='55', max_length=5, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='ERP_ServicesBI.pedidocompra', verbose_name='Pedido de Compra'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='serie',
            field=models.CharField(blank=True, default='1', max_length=5, verbose_name='Série'),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_entrada_cadastradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='usuario_cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_entrada_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='usuario_confirmacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_entrada_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='valor_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='notafiscalentrada',
            name='valor_produtos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='ERP_ServicesBI.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço'), ('materia_prima', 'Matéria Prima'), ('embalagem', 'Embalagem'), ('consumo', 'Material de Consumo')], default='produto', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='condicaopagamento',
            name='dias_primeira_parcela',
            field=models.IntegerField(default=0, verbose_name='Dias 1ª Parcela'),
        ),
        migrations.AlterField(
            model_name='condicaopagamento',
            name='periodicidade',
            field=models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='aliquota_csll',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='aliquota_irpj',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='aliquota_irpj_adicional',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='aliquota_simples',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='atividade_principal',
            field=models.CharField(choices=[('comercio', 'Comércio'), ('servico', 'Serviços'), ('industria', 'Indústria'), ('misto', 'Misto')], default='comercio', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_dre', to='ERP_ServicesBI.empresa'),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='percentual_presuncao_comercio',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='percentual_presuncao_servico',
            field=models.DecimalField(decimal_places=2, default=32.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaodre',
            name='regime_tributario',
            field=models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], default='simples', max_length=15),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='arquivo_origem',
            field=models.FileField(blank=True, null=True, upload_to='cotacoes_fornecedor/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='contato_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='contato_telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='cotacao_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_fornecedor', to='ERP_ServicesBI.cotacaomae'),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='disponibilidade_produtos',
            field=models.CharField(default='100%', max_length=50),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.fornecedor'),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='nota_confiabilidade',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='prazo_entrega_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('importada', 'Importada'), ('processada', 'Processada'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='valor_total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cotacaofornecedor',
            name='valor_total_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cotacaomae',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cotacaomae',
            name='data_limite_resposta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotacaomae',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotacaomae',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotacaomae',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_mae_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cotacaomae',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada aos Fornecedores'), ('respondida', 'Cotações Recebidas'), ('em_analise', 'Em Análise'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária'), ('cheque', 'Cheque'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='codigo_fornecedor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='cotacao_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ERP_ServicesBI.cotacaofornecedor'),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='descricao_fornecedor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='item_solicitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_recebidas', to='ERP_ServicesBI.itemsolicitado'),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='match_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='match_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='melhor_prazo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='melhor_preco',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cotacao_origem', to='ERP_ServicesBI.pedidocompra'),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='prazo_entrega_item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='selecionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='sugerido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemcotacaofornecedor',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='itemnotafiscalentrada',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.produto'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='data_ultimo_recebimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='divergencia_encontrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='item_cotacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido_gerados', to='ERP_ServicesBI.itemcotacaofornecedor'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='observacao_divergencia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ERP_ServicesBI.pedidocompra'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='preco_unitario_recebido',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='ERP_ServicesBI.produto'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='quantidade_conferida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='quantidade_recebida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='recebido_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='tipo_divergencia',
            field=models.CharField(blank=True, choices=[('quantidade_maior', 'Quantidade Maior que o Pedido'), ('quantidade_menor', 'Quantidade Menor que o Pedido'), ('preco_diferente', 'Preço Diferente do Pedido'), ('qualidade', 'Problema de Qualidade'), ('atraso', 'Atraso na Entrega'), ('produto_errado', 'Produto Errado'), ('avaria', 'Avaria no Transporte')], max_length=50),
        ),
        migrations.AlterField(
            model_name='itemsolicitado',
            name='cotacao_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitados', to='ERP_ServicesBI.cotacaomae'),
        ),
        migrations.AlterField(
            model_name='itemsolicitado',
            name='descricao_manual',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemsolicitado',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemsolicitado',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.produto'),
        ),
        migrations.AlterField(
            model_name='itemsolicitado',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemsolicitado',
            name='unidade_medida',
            field=models.CharField(default='UN', max_length=20),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='formula',
            field=models.CharField(blank=True, help_text='Fórmula de cálculo', max_length=500),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='grupos_dre',
            field=models.CharField(blank=True, help_text='Grupos separados por vírgula', max_length=500),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='natureza',
            field=models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('calculado', 'Calculado')], default='credito', max_length=20),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='negrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='regime_especifico',
            field=models.CharField(blank=True, choices=[('', 'Todos'), ('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('deducao', 'Dedução'), ('custo', 'Custo'), ('despesa', 'Despesa'), ('resultado', 'Resultado'), ('imposto', 'Imposto'), ('outros', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='linhadre',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('ajuste_entrada', 'Ajuste Entrada'), ('ajuste_saida', 'Ajuste Saída'), ('transferencia', 'Transferência')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='pedido_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_origem', to='ERP_ServicesBI.pedidocompra', verbose_name='Pedido Origem (legacy)'),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacao',
            name='acao',
            field=models.CharField(choices=[('aprovou', 'Aprovou'), ('rejeitou', 'Rejeitou'), ('encaminhou', 'Encaminhou')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacao',
            name='nivel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacao',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacao',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_aprovacoes', to='ERP_ServicesBI.pedidocompra'),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='aprovador_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_para_aprovar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='conta_pagar_gerada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='cotacao_fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerados', to='ERP_ServicesBI.cotacaofornecedor'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='cotacao_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerados', to='ERP_ServicesBI.cotacaomae'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='motivo_rejeicao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='movimento_estoque_gerado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='nivel_aprovacao_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='nivel_aprovacao_necessario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='nota_fiscal_vinculada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='observacao_recebimento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='prazo_entrega_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_aprovacao', 'Em Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('pendente_entrega', 'Pendente de Entrega'), ('parcial', 'Entrega Parcial'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='usuario_aprovacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='usuario_cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='usuario_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regraaprovacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='regraaprovacao',
            name='grupo_aprovador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_aprovacao', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='regraaprovacao',
            name='nivel',
            field=models.IntegerField(verbose_name='Nível de Aprovação'),
        ),
        migrations.AlterField(
            model_name='regraaprovacao',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='regraaprovacao',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='dados_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_dre', to='ERP_ServicesBI.empresa'),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='gerado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='gerado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_dre_gerados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='regime_tributario',
            field=models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=15),
        ),
        migrations.AlterField(
            model_name='relatoriodre',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('aprovado', 'Aprovado')], default='rascunho', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='comissao_padrao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissão Padrão (%)'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='meta_vendas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Meta de Vendas Mensal'),
        ),
        migrations.CreateModel(
            name='ContagemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_contada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_contagem', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('contado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_inventario', to=settings.AUTH_USER_MODEL)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens', to='ERP_ServicesBI.inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.produto')),
            ],
            options={
                'verbose_name': 'Contagem de Inventário',
                'verbose_name_plural': 'Contagens de Inventário',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='ERP_ServicesBI.deposito', verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='deposito_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_entrada', to='ERP_ServicesBI.deposito', verbose_name='Depósito Destino'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='deposito_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_saida', to='ERP_ServicesBI.deposito', verbose_name='Depósito Origem'),
        ),
        migrations.CreateModel(
            name='EntradaNFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nfe', models.CharField(max_length=50, verbose_name='Número NF-e')),
                ('serie', models.CharField(blank=True, default='1', max_length=5)),
                ('chave_acesso', models.CharField(blank=True, max_length=60, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_nfe', to='ERP_ServicesBI.deposito')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_nfe_estoque', to='ERP_ServicesBI.fornecedor')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_nfe', to='ERP_ServicesBI.pedidocompra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_nfe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada NF-e (Estoque)',
                'verbose_name_plural': 'Entradas NF-e (Estoque)',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntradaNFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ERP_ServicesBI.entradanfe')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ERP_ServicesBI.produto')),
            ],
            options={
                'verbose_name': 'Item Entrada NF-e',
                'verbose_name_plural': 'Itens Entrada NF-e',
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('custo_medio', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('data_ultimo_movimento', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='ERP_ServicesBI.deposito')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_por_deposito', to='ERP_ServicesBI.produto')),
            ],
            options={
                'verbose_name': 'Saldo de Estoque',
                'verbose_name_plural': 'Saldos de Estoque',
                'db_table': 'estoque_saldo',
                'ordering': ['produto__descricao', 'deposito__nome'],
                'unique_together': {('produto', 'deposito')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='ERP_ServicesBI.unidademedida', verbose_name='Unidade de Medida'),
        ),
        migrations.DeleteModel(
            name='ItemRelatorioDRE',
        ),
    ]
